### PR TITLE
Add missing `main` field

### PR DESCRIPTION
**Pull request by aryzing**
Added `main` field to `package.json`.

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@aryzing did this cause an issue for you?

> Note: Most modules have an index.js file as the main point of entry. This is the default value for a package.json’s main property, which is the point of entry for npm modules. If there is no package.json, Node.js will try to load index.js by default.

https://www.digitalocean.com/community/tutorials/how-to-use-node-js-modules-with-npm-and-package-json#step-1-%E2%80%94-creating-a-packagejson-file

**Comment by aryzing** [comment]
Unfortunately the lack of a `main` field [confuses snowpack](https://github.com/snowpackjs/snowpack/discussions/2487#discussioncomment-312682). Would it be an inconvenience to have a `main` field?

**Comment by ChristianMurphy** [comment]
At a general level, if a build tool does support standard npm behavior it feels off to try to patch that in various community packages, rather than in the build tool itself.
But more to your specific bug, snowpack already does (or claims to) support missing `main`, defaulting to _index.js_
https://github.com/snowpackjs/snowpack/blob/3efcffb7ea5761f84d771561109198413c89c5c3/esinstall/src/entrypoints.ts#L225-L228

**Comment by aryzing** [comment]
Seems it should, trying to clarify given I can very predictably replicate the behavior linked above. Agree that wouldn't want to touch `remark-frontmatter` unless necessary.

**Comment by wooorm** [comment]
I’d say this is something that Snowpack should fix: `remark-frontmatter` is one of *many* projects that has no `main` field.

**Comment by wooorm** [comment]
Closing as this sounds like an external problem.

**Pull request closed without merging**
